// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbqeywcebrxfdnzdldpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZicWV5d2NlYnJ4ZmRuemRsZHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDYwMjcsImV4cCI6MjA2NTI4MjAyN30.ZXV-iCQ87Wj3n9EIeARxVz3WTgScdwoFb1Fwrirn27o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);